/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* Do not edit this file as changes may cause incorrect behavior and will be lost
* once the code is regenerated.
*
* @generated by codegen project: GeneratePropsJavaInterface.js
*/

package com.facebook.react.viewmanagers;

import android.view.View;
import androidx.annotation.Nullable;

public interface GooglePayButtonManagerInterface<T extends View> {
  void setButtonType(T view, @Nullable String value);
  void setButtonStyle(T view, @Nullable String value);
  void setBorderRadius(T view, double value);
  void setAllowedPaymentMethods(T view, @Nullable String value);
}
