/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* Do not edit this file as changes may cause incorrect behavior and will be lost
* once the code is regenerated.
*
* @generated by codegen project: GeneratePropsJavaInterface.js
*/

package com.facebook.react.viewmanagers;

import android.view.View;
import androidx.annotation.Nullable;
import com.facebook.react.bridge.Dynamic;

public interface NativePaymentWidgetManagerInterface<T extends View> {
  void setWidgetId(T view, @Nullable String value);
  void setWidgetType(T view, @Nullable String value);
  void setClientSecret(T view, @Nullable String value);
  void setOptions(T view, @Nullable Dynamic value);
  void setSdkAuthorization(T view, @Nullable String value);
}
