/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* Do not edit this file as changes may cause incorrect behavior and will be lost
* once the code is regenerated.
*
* @generated by codegen project: GeneratePropsJavaDelegate.js
*/

package com.facebook.react.viewmanagers;

import android.view.View;
import androidx.annotation.Nullable;
import com.facebook.react.bridge.DynamicFromObject;
import com.facebook.react.uimanager.BaseViewManager;
import com.facebook.react.uimanager.BaseViewManagerDelegate;
import com.facebook.react.uimanager.LayoutShadowNode;
public class NativePaymentWidgetManagerDelegate<T extends View, U extends BaseViewManager<T, ? extends LayoutShadowNode> & NativePaymentWidgetManagerInterface<T>> extends BaseViewManagerDelegate<T, U> {
  public NativePaymentWidgetManagerDelegate(U viewManager) {
    super(viewManager);
  }
  @Override
  public void setProperty(T view, String propName, @Nullable Object value) {
    switch (propName) {
      case "widgetId":
        mViewManager.setWidgetId(view, value == null ? null : (String) value);
        break;
      case "widgetType":
        mViewManager.setWidgetType(view, value == null ? null : (String) value);
        break;
      case "clientSecret":
        mViewManager.setClientSecret(view, value == null ? null : (String) value);
        break;
      case "sdkAuthorization":
        mViewManager.setSdkAuthorization(view, value == null ? null : (String) value);
        break;
      case "options":
        mViewManager.setOptions(view, new DynamicFromObject(value));
        break;
      default:
        super.setProperty(view, propName, value);
    }
  }
}
