
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleJavaSpec.js
 *
 * @nolint
 */

package com.hyperswitchsdkreactnative;

import com.facebook.proguard.annotations.DoNotStrip;
import com.facebook.react.bridge.Callback;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.bridge.ReadableMap;
import com.facebook.react.turbomodule.core.interfaces.TurboModule;
import javax.annotation.Nonnull;

public abstract class NativeHyperswitchSdkNativeSpec extends ReactContextBaseJavaModule implements TurboModule {
  public static final String NAME = "HyperModule";

  public NativeHyperswitchSdkNativeSpec(ReactApplicationContext reactContext) {
    super(reactContext);
  }

  @Override
  public @Nonnull String getName() {
    return NAME;
  }

  @ReactMethod
  @DoNotStrip
  public abstract void sendMessageToNative(String message);


  @ReactMethod
  @DoNotStrip
  public abstract void startApplePay(String requestObj, Callback callback);

  @ReactMethod
  @DoNotStrip
  public abstract void presentApplePay(String requestObj, Callback callback);

  @ReactMethod
  @DoNotStrip
  public abstract void launchApplePay(String requestObj, Callback callback);

  @ReactMethod
  @DoNotStrip
  public abstract void launchGPay(String requestObj, Callback callback);

  @ReactMethod
  @DoNotStrip
  public abstract void exitPaymentsheet(double rootTag, String result, boolean reset);

  @ReactMethod
  @DoNotStrip
  public abstract void exitPaymentMethodManagement(double rootTag, String result, boolean reset);

  @ReactMethod
  @DoNotStrip
  public abstract void exitWidget(String result, String widgetType);

  @ReactMethod
  @DoNotStrip
  public abstract void exitCardForm(String result);

  @ReactMethod
  @DoNotStrip
  public abstract void exitWidgetPaymentsheet(double rootTag, String widgetId, String result, boolean reset);

  @ReactMethod
  @DoNotStrip
  public abstract void launchWidgetPaymentSheet(String requestObj, Callback callback);

  @ReactMethod
  @DoNotStrip
  public abstract void updateWidgetHeight(double height);

  @ReactMethod
  @DoNotStrip
  public abstract void emitPaymentEvent(String widgetId, String eventType, ReadableMap payload);

  @ReactMethod
  @DoNotStrip
  public abstract void onAddPaymentMethod(String data);
}
