//
//  NativePaymentElementModule.mm
//
//  TurboModule (New Architecture) for NativePaymentElementModule.
//  Module name: "NativePaymentElementModule"
//
//  Matches Android's NativePaymentWidgetModule (NativePaymentElementModuleSpec):
//    confirmPayment(reactTag, callback)
//    updateIntentInitForWidget(reactTag, callback)
//    updateIntentCompleteForWidget(reactTag, sdkAuthorization, callback)
//
//  Old arch (bridge): the view-manager commands (same methods) live on NativePaymentWidget
//                     (RCTViewManager) which is accessible via NativeModules.NativePaymentWidget.
//                     NativeHyperswitchSdk.ts still uses that path, so both old and new arch work.
//
//  New arch (TurboModule): this module is registered as "NativePaymentElementModule" and is
//                          the spec-compliant TurboModule counterpart.  It delegates to the
//                          inner NativePaymentWidgetView found via NativePaymentWidgetViewRegistry.
//

#import <React/RCTBridgeModule.h>
#import <React/RCTUIManager.h>

#if __has_include("HyperswitchSdkReactNative-Swift.h")
#import "HyperswitchSdkReactNative-Swift.h"
#else
#import <HyperswitchSdkReactNative/HyperswitchSdkReactNative-Swift.h>
#endif

#import "NativePaymentWidgetViewRegistry.h"

#ifdef RCT_NEW_ARCH_ENABLED
#import <HyperswitchSdkReactNativeSpec/HyperswitchSdkReactNativeSpec.h>
#endif

// ─────────────────────────────────────────────────────────────────────────────
// Private helper: find NativePaymentWidgetView by React tag.
//
// Checks NativePaymentWidgetViewRegistry first (covers both old-arch direct
// NativePaymentWidgetView instances registered there AND the inner widget views
// registered by NativePaymentElementView for Fabric).
// ─────────────────────────────────────────────────────────────────────────────
static NativePaymentWidgetView * _Nullable widgetViewForTag(NSNumber *tag)
{
    UIView *v = [[NativePaymentWidgetViewRegistry shared] viewForTag:tag];
    return [v isKindOfClass:[NativePaymentWidgetView class]]
        ? (NativePaymentWidgetView *)v
        : nil;
}

// ─────────────────────────────────────────────────────────────────────────────

// Use RCTBridgeModule for both arches; getTurboModule: below handles new arch wiring.
@interface NativePaymentElementModule : NSObject <RCTBridgeModule>
@end

@implementation NativePaymentElementModule

RCT_EXPORT_MODULE(NativePaymentElementModule)

// ── confirmPayment ────────────────────────────────────────────────────────────
// JS / Android: confirmPayment(reactTag: number, callback)
// Mirrors Android NativePaymentWidgetModule.confirmPayment (mostly a stub there).
// On iOS we do the real work via the shared registry.
RCT_EXPORT_METHOD(confirmPayment:(double)reactTag
                  callback:(RCTResponseSenderBlock)callback)
{
    NSNumber *tag = @((NSInteger)reactTag);
    dispatch_async(dispatch_get_main_queue(), ^{
        NativePaymentWidgetView *view = widgetViewForTag(tag);
        if (view) {
            [view confirmPayment:callback];
        } else {
            callback(@[@{@"status": @"failed",
                         @"code":   @"WIDGET_NOT_FOUND",
                         @"message": [NSString stringWithFormat:@"Widget not found for tag %@", tag]}]);
        }
    });
}

// ── updateIntentInitForWidget ─────────────────────────────────────────────────
RCT_EXPORT_METHOD(updateIntentInitForWidget:(double)reactTag
                  callback:(RCTResponseSenderBlock)callback)
{
    NSNumber *tag = @((NSInteger)reactTag);
    dispatch_async(dispatch_get_main_queue(), ^{
        NativePaymentWidgetView *view = widgetViewForTag(tag);
        if (view) {
            [view updateIntentInit:callback];
        } else {
            callback(@[@{@"status": @"failed",
                         @"code":   @"WIDGET_NOT_FOUND",
                         @"message": [NSString stringWithFormat:@"Widget not found for tag %@", tag]}]);
        }
    });
}

// ── updateIntentCompleteForWidget ─────────────────────────────────────────────
RCT_EXPORT_METHOD(updateIntentCompleteForWidget:(double)reactTag
                  sdkAuthorization:(NSString *)sdkAuthorization
                  callback:(RCTResponseSenderBlock)callback)
{
    NSNumber *tag = @((NSInteger)reactTag);
    dispatch_async(dispatch_get_main_queue(), ^{
        NativePaymentWidgetView *view = widgetViewForTag(tag);
        if (view) {
            [view updateIntentCompleteWithSdkAuthorization:sdkAuthorization resolve:callback];
        } else {
            callback(@[@{@"status": @"failed",
                         @"code":   @"WIDGET_NOT_FOUND",
                         @"message": [NSString stringWithFormat:@"Widget not found for tag %@", tag]}]);
        }
    });
}

// ── TurboModule wiring (New Architecture) ─────────────────────────────────────
// NativePaymentElementModuleSpecJSI is generated by iOS codegen from
// NativePaymentElementModule.ts  →  HyperswitchSdkReactNativeSpec pod.
#ifdef RCT_NEW_ARCH_ENABLED
- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params
{
    return std::make_shared<facebook::react::NativePaymentElementModuleSpecJSI>(params);
}
#endif

+ (BOOL)requiresMainQueueSetup { return NO; }

@end
